### ISSUE TITLE
Upgrade to ASP.NET Core 1.0 RTM

### ISSUE THREAD

**Issue by afuersch** [saxx/Wuzlstats#11]
Helpful sources: http://www.elanderson.net/2015/11/migration-from-asp-net-5-beta-8-to-rc1/

**Comment by afuersch** [comment]
Seems like signalR is not working correctly after upgrading to RC1.
After entering a score, the score is saved, but the ranking list is not updated.

**Comment by saxx** [comment]
Hmm, weird. Did you make sure that the JS libraries are on the latest version as well?

I know that SignalR is more or less "ignored" since one of the first betas, it _should_ work but ... well.

Could you double-check your current implementation, maybe open an issue in the official signalr repo?

**Update**
Since saving of the score works (also using SignalR), it's even weirder. Did you debug it? Would the hub fire its update correctly on the server-side?

**Comment by saxx** [comment]
@afuersch _push_ How about you take another look. I don't want to support old DNX stuff on the server anymore?

**Comment by saxx** [comment]
@afuersch Thank you! I had to do a few minor tweaks, but your version is up an running now. Automatic deployment is working as well, so feel free to add new features ;-)
